# Generated by Django 2.2.2 on 2023-02-20 20:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('Id', models.IntegerField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200)),
                ('Posted_by', models.CharField(max_length=200)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('content', models.TextField()),
                ('category', models.CharField(choices=[('RP', 'Resendential Project'), ('HS', 'Housing Society'), ('RSK', 'Real Estate Knowledge'), ('CU', 'Construction Update')], max_length=200)),
            ],
            options={
                'ordering': ['-created_on'],
            },
        ),
        migrations.CreateModel(
            name='Images',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='images')),
                ('note', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mycompany.Post')),
            ],
        ),
    ]
