# Generated by Django 2.2.2 on 2023-04-04 20:44

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mycompany', '0004_mail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mail',
            name='text',
            field=ckeditor.fields.RichTextField(),
        ),
        migrations.AlterField(
            model_name='post',
            name='content',
            field=ckeditor.fields.RichTextField(),
        ),
    ]
