# Generated by Django 2.2.2 on 2023-04-06 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mycompany', '0005_auto_20230405_0144'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Mail',
        ),
        migrations.AddField(
            model_name='post',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images'),
        ),
    ]
